# Generated by Django 4.2.5 on 2023-10-04 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="birth_data",
            new_name="birth_date",
        ),
    ]
